apiVersion: v1
kind: Service
metadata:
  name: pages
  labels:
    app: nginx-mra
    component: pages
  namespace: nginx-mra
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 9600
    targetPort: 9600
    protocol: TCP
    name: ls-api
  - port: 5544
    targetPort: 5544
    protocol: TCP
    name: syslog
  selector:
    app: nginx-mra
    component: pages
