apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: nginx-mra
    component: redis
  namespace: nginx-mra
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp
  selector:
    app: nginx-mra
    component: redis
