name: pages
resolver:
  host: kube-dns.kube-system.svc.cluster.local
  ttl: 1s
root: /ingenious-pages/web
external_domain_name: k8s.mra.nginxps.com
internal_domain_name: svc.cluster.local
namespace: nginx-mra
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: pages_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=pages_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
services:
  album-manager:
    server: svc.cluster.local
    service: 'service=_https._tcp.album-manager'
    expose_external: true
    healthcheck: true
    port: 443
  content-service:
    server: svc.cluster.local
    service: 'service=_https._tcp.content-service'
    expose_external: true
    healthcheck: true
    port: 443
  uploader:
    server: svc.cluster.local
    service: 'service=_https._tcp.uploader'
    expose_external: true
    healthcheck: true
    port: 443
  user-manager:
    server: svc.cluster.local
    service: 'service=_https._tcp.user-manager'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
    port: 443
